---
- name: Обновление ИМС
  hosts: elina
  become: yes
  vars_files: vars
  gather_facts: no
  tasks:
#    - name: Удаление старых обновляемых файлов
#      file: 
#         path: "{{ eims_path }}/{{ item }}" 
#         state: absent 
#      with_items:
#           - bin
#           - sdk
#           - rlibs
#           - bm
#           - log
#           - plugins
#           - xml
#           - whatisit.txt

    - name: Установка новых файлов
      unarchive:
         src: eims.tar.gz
         dest: "{{ rusbitech_path }}"
         owner: "{{ user }}"
         group: users
         mode: '0777'    
      

    
  